apiVersion: awx.ansible.com/v1beta1
kind: AWXCredential
metadata:
  name: github-scm
spec:
  organization: Default
  credential_type: Source Control
  inputs:
    username: Starslider
    password:
      valueFrom:
        secretKeyRef:
          name: github-pat
          key: token
