apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubeuser-password
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kubeuser-password
        metadataPolicy: None
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kubeuser-password
        metadataPolicy: None
        property: username
      secretKey: username
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
