apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  bootstrap:
    initdb:
      database: app
      owner: app

  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cluster-pooler
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: postgres-cluster
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "20"
