apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-satisfactory
  namespace: satisfactory
spec:
  concurrencyPolicy: Forbid
  schedule: '0 5 * * *' # Daily at 05:00
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: satisfactory-svc
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/satisfactory'
