---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      volumes:
        - name: satisfactory-config
          persistentVolumeClaim:
            claimName: satisfactory-config-pvc
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: satisfactory-config
              mountPath: /config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAXPLAYERS
              value: "8"
            - name: STEAMBETA
              value: "false"
            - name: AUTOSAVENUM
              value: "5"
            - name: DEBUG
              value: "false"
            - name: DISABLESEASONALEVENTS
              value: "false"
            - name: SERVERGAMEPORT
              value: "7777"
            - name: SERVERMESSAGINGPORT
              value: "8888"
            - name: SERVERSTREAMING
              value: "true"
            - name: SKIPUPDATE
              value: "false"
          ports:
            - name: game-udp
              containerPort: 7777
              protocol: UDP
            - name: game-tcp
              containerPort: 7777
              protocol: TCP
            - name: messaging
              containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "16Gi"
