---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: satisfactory
  name: satisfactory-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
