# Control-plane VMAgent with inline scrape configs
# Uses inlineScrapeConfig instead of VMStaticScrape because the main VMAgent
# (victoria-metrics-k8s-stack) has selectAllByDefault: true and claims all
# VMStaticScrape resources first. inlineScrapeConfig bypasses this mechanism.
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: control-plane-vmagent
  namespace: monitoring
spec:
  daemonSetMode: true
  selectAllByDefault: false
  # Disable all scrape object selection - we use inlineScrapeConfig instead
  serviceScrapeSelector:
    matchLabels:
      non-existent-label: "disabled"
  podScrapeSelector:
    matchLabels:
      non-existent-label: "disabled"
  staticScrapeSelector:
    matchLabels:
      non-existent-label: "disabled"
  # Inline scrape configs for control-plane components
  # These targets bind to localhost only, so hostNetwork: true is required
  inlineScrapeConfig: |
    - job_name: kube-scheduler
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      static_configs:
        - targets: ["localhost:10259"]
    - job_name: kube-controller-manager
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      static_configs:
        - targets: ["localhost:10257"]
    - job_name: kube-etcd
      scheme: http
      static_configs:
        - targets: ["localhost:2381"]
  remoteWrite:
  - url: http://vmsingle-monitoring-victoria-metrics-k8s-stack:8428/api/v1/write
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  scrapeInterval: "30s"
  scrapeTimeout: "10s"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
