apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: control-plane-metrics
  namespace: monitoring
  labels:
    control-plane: "true"
spec:
  jobName: "control-plane-metrics"
  targetEndpoints:
  - targets:
    - "127.0.0.1:10259"  # kube-scheduler HTTPS metrics via localhost
    labels:
      job: kube-scheduler
      component: kube-scheduler
      tier: control-plane
      instance: arch-kubernetes-control-plane
    path: /metrics
    scheme: https
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
  - targets:
    - "127.0.0.1:10257"  # kube-controller-manager HTTPS metrics via localhost
    labels:
      job: kube-controller-manager
      component: kube-controller-manager
      tier: control-plane
      instance: arch-kubernetes-control-plane
    path: /metrics
    scheme: https
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true