apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: control-plane-vmagent
  namespace: monitoring
spec:
  selectAllByDefault: false
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  staticScrapeSelector:
    matchLabels:
      control-plane: "true"
  remoteWrite:
  - url: http://vmsingle-monitoring-victoria-metrics-k8s-stack:8429/api/v1/write
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  scrapeInterval: "30s"
  scrapeTimeout: "10s"
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
      cpu: "100m"
