apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: control-plane-vmagent
  namespace: monitoring
spec:
  selectAllByDefault: false
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  staticScrapeSelector:
    matchLabels:
      control-plane: "true"
  remoteWrite:
  - url: http://vmsingle-monitoring-victoria-metrics-k8s-stack:8429/api/v1/write
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  scrapeInterval: "30s"
  scrapeTimeout: "10s"
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
      cpu: "100m"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: control-plane-localhost
  namespace: monitoring
  labels:
    control-plane: "true"
spec:
  jobName: "control-plane-localhost"
  targetEndpoints:
  - targets:
    - "127.0.0.1:10251"  # kube-scheduler health/ready endpoints
    labels:
      job: kube-scheduler-health
      component: kube-scheduler
      tier: control-plane
    path: /healthz
    scheme: http
    interval: 30s
  - targets:
    - "127.0.0.1:10252"  # kube-controller-manager health endpoints  
    labels:
      job: kube-controller-manager-health
      component: kube-controller-manager
      tier: control-plane
    path: /healthz
    scheme: http
    interval: 30s