apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: control-plane-vmagent
  namespace: monitoring
spec:
  replicaCount: 1
  selectAllByDefault: false
  serviceScrapeSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values: [victoria-metrics-k8s-stack]
    - key: jobLabel
      operator: NotIn
      values: [kube-etcd]
  podScrapeSelector: {}
  staticScrapeSelector:
    matchLabels:
      control-plane: "true"
  remoteWrite:
  - url: http://vmsingle-monitoring-victoria-metrics-k8s-stack:8429/api/v1/write
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  scrapeInterval: "30s"
  scrapeTimeout: "10s"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
