apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-secret
  namespace: monitoring
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    name: discord-webhook-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord-alert-webhook
        property: webhook
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None