apiVersion: batch/v1
kind: Job
metadata:
  name: enable-control-plane-metrics
  namespace: monitoring
spec:
  template:
    spec:
      hostPID: true
      hostNetwork: true
      nodeName: arch-kubernetes-control-plane
      containers:
      - name: enable-metrics
        image: busybox
        command:
        - sh
        - -c
        - |
          # Enable metrics for kube-scheduler
          if grep -q "kube-scheduler.yaml" /etc/kubernetes/manifests/kube-scheduler.yaml; then
            sed -i '/--bind-address=0.0.0.0/a\      --port=10251' /etc/kubernetes/manifests/kube-scheduler.yaml
          fi
          
          # Enable metrics for kube-controller-manager
          if grep -q "kube-controller-manager.yaml" /etc/kubernetes/manifests/kube-controller-manager.yaml; then
            sed -i '/--bind-address=0.0.0.0/a\      --port=10252' /etc/kubernetes/manifests/kube-controller-manager.yaml
          fi
          
          # Restart kubelet to reload static pods
          pkill -HUP kubelet
        securityContext:
          privileged: true
        volumeMounts:
        - name: manifests
          mountPath: /etc/kubernetes/manifests
      volumes:
      - name: manifests
        hostPath:
          path: /etc/kubernetes/manifests
      restartPolicy: Never