# etcd exposes metrics on a separate HTTP endpoint (no TLS, no auth required)
# Port 2381 is the metrics-only port configured via --listen-metrics-urls
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: etcd-metrics
  namespace: monitoring
  labels:
    control-plane: "true"
spec:
  jobName: kube-etcd
  targetEndpoints:
    - targets:
        - "localhost:2381"
      scheme: http