apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: etcd-metrics
  namespace: monitoring
  labels:
    control-plane: "true"
spec:
  endpoints:
  - port: http-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: monitoring-victoria-metrics-k8s-stack-kube-etcd
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: victoria-metrics-k8s-stack
      jobLabel: kube-etcd