apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-id
      remoteRef:
        key: grafana-oauth
        property: client-id
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
    - secretKey: client-secret
      remoteRef:
        key: grafana-oauth
        property: client-secret
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None