apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.loki.svc.cluster.local:80
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
