apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: openclaw-policy
  namespace: openclaw
spec:
  endpointSelector:
    matchLabels:
      app: openclaw
  ingress:
  # Allow traffic from ingress namespace (Gateway / oauth2-proxy)
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: ingress
  # Allow intra-namespace traffic (oauth2-proxy sidecar)
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: openclaw
  egress:
  # DNS resolution via kube-dns
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  # xAI Grok API (104.18.18.0/23 covers Cloudflare range for api.x.ai)
  - toCIDRSet:
    - cidr: 104.18.18.0/23
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  # Telegram Bot API (149.154.160.0/20 covers Telegram's DC range)
  - toCIDRSet:
    - cidr: 149.154.160.0/20
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  # Authentik OIDC (local network for oauth2-proxy token validation)
  - toCIDRSet:
    - cidr: 192.168.1.210/32
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
