apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cloudflare-api-key
        metadataPolicy: None
        property: apiKey
      secretKey: apiKey
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
