apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ollama

resources:
  - runtimeclass-nvidia.yaml
  - operator-image-patch.yaml
  - ollama-store-image-patch.yaml
  - ollama-model.yaml
  - ollama-model-service.yaml
  - model-server-image-patch.yaml
  - model-warmup-cronjob.yaml

