apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ollama

resources:
  - runtimeclass-nvidia.yaml
  - ollama-gpu.yaml
  - ollama-model.yaml
  - ollama-model-service.yaml
  - model-warmup-cronjob.yaml
