apiVersion: batch/v1
kind: CronJob
metadata:
  name: ollama-model-warmup
  namespace: ollama-operator-system
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: warmup
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              curl -s -X POST http://ollama-models-store.ollama-operator-system:11434/api/generate \
                -H "Content-Type: application/json" \
                -d '{"model":"qwen2.5:3b","prompt":"ping","stream":false}' \
                --max-time 30 > /dev/null && echo "Model warmed up successfully"
          restartPolicy: OnFailure
