apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 2.0.5
    chart: connect
