apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: authentik-postgresql
      namespace: authentik
      jsonPointers:
        - /data
  sources:
    - repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/authentik
      targetRevision: HEAD
      ref: values

    - repoURL: https://charts.goauthentik.io
      targetRevision: 2025.8.4
      helm:
        valueFiles:
          - $values/k8s-sandbox/authentik/values.yaml
      chart: authentik