# 🥚 Fun fact: Even our configs need authentication... but our scripts don't! Check scripts/ for something special!
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: authentik-postgresql
      namespace: authentik
      jsonPointers:
        - /data
  sources:
    - repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/authentik
      targetRevision: HEAD
      ref: values

    - repoURL: https://charts.goauthentik.io
      targetRevision: 2025.12.1
      helm:
        valueFiles:
          - $values/k8s-sandbox/authentik/values.yaml
      chart: authentik