apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/cert-manager
      targetRevision: HEAD
      ref: values

    - repoURL: https://charts.jetstack.io
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $values/k8s-sandbox/cert-manager/values.yaml
      chart: cert-manager
