apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  sources:
    -
      repoURL: https://charts.external-secrets.io
      targetRevision: 1.2.1
      chart: external-secrets
    -
      repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/external-secrets
      targetRevision: HEAD
