apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flatcar-linux-update-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/flatcar/flatcar-linux-update-operator.git
    path: examples/deploy
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: reboot-coordinator