apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hp-wmi-sensors
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/Starslider/kubernetes-demo.git
    path: k8s-sandbox/hp-wmi-sensors
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
