apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-workshop
  annotations:
    # Enable image updater
    argocd-image-updater.argoproj.io/image-list: workshop=ghcr.io/starslider/kubernetes-demo/k8s-workshop
    # Use newest-build strategy (renamed from latest)
    argocd-image-updater.argoproj.io/workshop.update-strategy: newest-build
    # Don't write back to git, just update in ArgoCD (for faster updates)
    argocd-image-updater.argoproj.io/write-back-method: argocd
    # Allow tags matching this pattern (optional - tracks both latest and SHA tags)
    argocd-image-updater.argoproj.io/workshop.allow-tags: regexp:^(latest|main-[a-f0-9]{7})$
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-workshop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/Starslider/kubernetes-demo.git
    path: k8s-sandbox/k8s-workshop
    targetRevision: HEAD
