apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.49.0
    helm:
      valuesObject:
        # Single binary mode with filesystem storage
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        # Disable dependencies we manage separately
        minio:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          serviceMonitor:
            enabled: true
        # Single binary deployment
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
        # Disable scalable components
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        # Enable gateway for external access
        gateway:
          enabled: true
          replicas: 1
        # Disable network policies that might block traffic
        networkPolicy:
          enabled: false
    chart: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
