apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  sources:
  - repoURL: https://charts.min.io/
    targetRevision: 5.4.0
    helm:
      valueFiles:
        - $values/k8s-sandbox/minio/custom-values.yaml
    chart: minio
  - repoURL: https://github.com/Starslider/kubernetes-demo.git
    path: k8s-sandbox/minio
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: minio
    namespace: minio
    jsonPointers:
    - /data
  - group: "apps"
    kind: Deployment
    name: minio
    namespace: minio
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secrets
    - /spec/template/metadata/annotations/checksum~1config