apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.27.0
      chart: cloudnative-pg
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
    - repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/postgres
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
