apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0
    helm:
      parameters:
        - name: serviceMonitor.enabled
          value: 'true'
        - name: config.clients[0].url
          value: 'http://loki-loki-distributed-gateway/loki/api/v1/push'
    chart: promtail
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
