apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
  sources:
    - repoURL: oci://ghcr.io/mkilchhofer/unifi-chart
      targetRevision: 1.16.0
      helm:
        valueFiles:
          - $values/k8s-sandbox/unifi/values.yaml
      chart: unifi

    - repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/unifi
      targetRevision: HEAD
      ref: values
