apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  # storageClassName: ""  # uncomment and set if you need a specific class (e.g. your nfs or longhorn class)