apiVersion: v1
kind: Service
metadata:
  name: unifi
  labels:
    app.kubernetes.io/name: unifi-os-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unifi.dhlabs.org
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: webui
      port: 11443
      targetPort: webui
      protocol: TCP
    - name: communication
      port: 8080
      targetPort: communication
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: stun
      protocol: UDP
    - name: discovery
      port: 10003
      targetPort: discovery
      protocol: UDP
  selector:
    app: unifi-os-server