apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-devops-credentials
  namespace: kmcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    name: azure-devops-credentials
  data:
    - secretKey: organization
      remoteRef:
        key: azure-devops
        property: organization
    - secretKey: token
      remoteRef:
        key: azure-devops
        property: token
