apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: azure-devops-mcp
spec:
  transportType: http
  httpTransport:
    targetPort: 5050
  deployment:
    image: ghcr.io/jordiag/azure-devops-mcp-server:latest
    port: 5050
    secretRefs:
      - name: azure-devops-credentials
