apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - unifi.dhlabs.org
  rules:
    - backendRefs:
        - kind: Service
          name: unifi-os-server-webui-svc
          port: 80
          namespace: unifi
