apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: k8s-workshop-grant
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: ingress
  to:
  - group: ""
    kind: Service
    name: k8s-workshop
