apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
      repoURL: https://github.com/Starslider/kubernetes-demo.git
      path: k8s-sandbox/apps
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

