apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-2090846200
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: repo-2090846200
        metadataPolicy: None
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: repo-2090846200
        metadataPolicy: None
        property: project
      secretKey: project
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: repo-2090846200
        metadataPolicy: None
        property: type
      secretKey: type
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: repo-2090846200
        metadataPolicy: None
        property: url
      secretKey: url
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: repo-2090846200
        metadataPolicy: None
        property: username
      secretKey: username
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
