apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-admin-secret
  namespace: minio
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    name: minio-admin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: rootPassword
      remoteRef:
        key: minio-admin
        property: root-password
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None