apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: dhlabs
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password:8080
      vaults:
        dhlabs: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets