apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: onepassword-connect-token
        metadataPolicy: None
        property: token
      secretKey: token
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain